### ISSUE TITLE
Does not commit bumped version number in package.json on Bitbucket pipelines

### ISSUE THREAD

**Issue by danobot** [conventional-changelog/standard-version#434]
I am having trouble using this in Bitbucket pipeline. It is consistently committing the changelog witout committing the package.json and the bumped version number.(Resulting in the same release version each time).
I treied:
* useing barebones configuration to call only `standard-version` without any flags.
* adding the --commit-all and -a flag
* manually calling `git add package.json` in `precommit` and `release` hook.
* removed all hooks

It works perfectly in local environment, I am not sure what I am missing.

Release Commit:
![image](https://user-images.githubusercontent.com/7984567/63205587-38822400-c0d9-11e9-9cd9-ec1ce4d36d0c.png)

**Package.json**
```
"scripts": {
    "release": "standard-version --no-verify --prerelease beta"
}, 
...
 "standard-version": {
    "scripts": {
      "postbump": "git add package.json",
      "precommit": "echo \"[skip ci]\""
    },
    "skip": {
      "tag": true
    }
  }
```

**Bitbucket PIpeline**
```

# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - echo "Hi"
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run release
            - git push origin master
```

**Comment by tokenvolt** [comment]
I'm having the same issue, but with GitLab CI. Version is not getting bumped in package.json.

**Comment by tokenvolt** [comment]
Nevermind it was a bug on our side, due to incorrect `.gitignore`

**Comment by zgreen** [comment]
Had the exact same issue in a bitbucket pipeline; `package.json` was never updated, even though it worked perfectly locally. I have no idea why. If I had to guess, I'd say it's a bitbucket issue.

In the end, I wrote a script to do it. Since `standard-release` does set the proper git tags, you can read those and update `package.json` appropriately:

```
// updatePkg.js
const fs = require("fs-extra");
const child_process = require("child_process");
const pkg = require("../package.json");

const main = async () => {
  const tag = child_process
    .execSync(`git describe --abbrev=0`, { encoding: "utf8" })
    .trim();
  pkg.version = tag.slice(1);
  try {
    await fs.writeJson("./package.json", pkg, { spaces: 2 });
  } catch (err) {
    throw err;
  }
  console.log(`package.json updated, version ${pkg.version}`);
  child_process.execSync(
    `git commit -am "chore(package.json): bump version [skip ci]"`
  );
  console.log("package.json update commited");
  child_process.execSync("git push");
  console.log("package.json update pushed");
};

main();
```

And the pipeline:
```
release: &release
  step:
    name: Release
    script:
      - npm i
      - npm run release
      - git push --follow-tags
      - npm run update:pkg
      - pipe: atlassian/npm-publish:0.2.5
        variables:
          NPM_TOKEN: $NPM_TOKEN
```
