### ISSUE TITLE
Include AppVeyor CI config for windows test

### ISSUE THREAD

**Issue by Tapppi** [conventional-changelog/standard-version#57]
As was pointed out by @bcoe in #55 it would be great to have AppVeyor run windows tests. Merging TravisCI and AppVeyor coverage is not so simple though (see lemurheavy/coveralls-public/issues/613).
Suggested base config was https://github.com/yargs/yargs-parser/blob/master/appveyor.yml. 

Some modifications:  
* Added core.autocrlf true to enforce CRLF line endings for the test.
* Added `nodejs_version: '0.10'` as it is present in travis.yml as well.
* Switched v5 to v6 as its the latest, is there some real need to include v5?
* Any need for `shallow_clone: true` and `clone_depth: 1`? Removed them for now.

So that leaves us with:
```
# Fix line endings on Windows
init:
  - git config --global core.autocrlf true
environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
    - nodejs_version: '0.10'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - npm test
```

On a related note, the travis.yml should probably include node version 4 as well as the latest (v6)?
